language: python
python:
  - "3.8"
  - "3.9"
  - "3.10"

before_install:
  - pip install --upgrade pip
  - pip install pytest-cov
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - export PATH="$HOME/.poetry/bin:$PATH"

install:
  - poetry install

script:
  - pytest --cov=./

after_success:
  - bash <(curl -s https://codecov.io/bash)
